// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SelbuttonsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void selbuttons() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1600, 860));
    driver.findElement(By.cssSelector(".col-sm .btn-light")).click();
    driver.findElement(By.cssSelector(".col-sm .btn-light")).click();
    driver.findElement(By.cssSelector(".col-sm .btn-light")).sendKeys("super");
    driver.findElement(By.cssSelector(".btn-info:nth-child(2)")).click();
    driver.findElement(By.name("title")).click();
    driver.findElement(By.name("title")).sendKeys("test2");
    driver.findElement(By.name("length")).click();
    driver.findElement(By.name("length")).sendKeys("123");
    driver.findElement(By.cssSelector(".btn-info:nth-child(3)")).click();
    assertThat(driver.switchTo().alert().getText(), is("you added: \n FILM: test2 \n LENGTH: 123"));
    driver.switchTo().alert().accept();
    driver.findElement(By.name("film_id")).click();
    driver.findElement(By.name("film_id")).sendKeys("1044");
    driver.findElement(By.cssSelector(".btn-danger")).click();
    assertThat(driver.switchTo().alert().getText(), is("you removed: \n FILM with Id: 1044"));
    driver.switchTo().alert().accept();
    driver.findElement(By.cssSelector(".text-center:nth-child(3) form")).click();
  }
}
